### ISSUE TITLE
why i got this error, when the warmup epoches ends. 

### ISSUE THREAD

**Issue by ziming-liu** [ildoonet/pytorch-gradual-warmup-lr#1]
`  File "train_mesh.py", line 266, in main
    scheduler_warmup.step()
  File "/home/liuziming/anaconda3/lib/python3.6/site-packages/warmup_scheduler/scheduler.py", line 39, in step
    return super(GradualWarmupScheduler, self).step(epoch)
  File "/home/liuziming/anaconda3/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 52, in step
    for param_group, lr in zip(self.optimizer.param_groups, self.get_lr()):
  File "/home/liuziming/anaconda3/lib/python3.6/site-packages/warmup_scheduler/scheduler.py", line 30, in get_lr
    return self.after_scheduler.get_lr()
AttributeError: 'ReduceLROnPlateau' object has no attribute 'get_lr'
`

when warmup epoches ends. i got this error. it use the examples as u shows.  and  run a simple resnet50 of torchvision

**Comment by ziming-liu** [comment]
I use another LR scheduler  it is OK, maybe there are some problem with ReduceLROnPlateau'???

**Comment by LotuSrc** [comment]
I think the code is not strong. For ReduceLROnPlateau, you need to remove return self.after_scheduler.get_lr(), or you can add some conditional judgement to distinguish ReduceLROnPlateau and other lr scheduler.

**Comment by shuoyangd** [comment]
I don't think `get_lr` is designed to be an accessible interface for all schedulers. See [this issue](https://github.com/pytorch/pytorch/issues/2829).
